### PR TITLE
`devicePublicKey` => `devicePubKey`

### PR DESCRIPTION
**Pull request by agektmr**
Trivial update aligning the extension name to the spec.

### CODE REVIEW

**Comment by MasterKale** [comment]
Hmm, there are a few unit tests that continue to reference the now "old" value `devicePublicKey`:

Screen Shot 2022-08-09 at 9 10 50 AM

Can you update these tests so everything refers to this extension as `devicePubKey` as well?

**Comment by agektmr** [comment]
Sorry, I overlooked your comment. Will fix them.

**Comment by agektmr** [comment]
@MasterKale Updated the tests. Can you check?

**Comment by MasterKale** [comment]
lgtm :shipit:

**Review by MasterKale — APPROVED** [review]

**Comment by MasterKale** [comment]
There's no issue associated with this so I'll let you know here that this is now available in **@simplewebauthn/server@5.4.5**.

**Pull request merged**
