### PR TITLE
fix: add missing type defs to example package.json

### PR DESCRIPTION
**Pull request by jstewmon**

### CODE REVIEW

**Comment by MasterKale** [comment]
@jstewmon Can I trouble you to also include `@types/node` in this PR as well? I think types in the monorepo's package.json are being picked up when I run any `npm` commands within **example/**, and when I isolate this project into an external folder and try to build it TypeScript complains about the missing Node types as well as the other two you're adding here.

**Comment by jstewmon** [comment]
Sure, no problem. Which version of node do you want to target? The major version of `@types/node` should correspond to the node major version.

**Comment by MasterKale** [comment]
CI tests 12 and 14, so let's go with 14 for now since this is an example server and it can be a little more liberal with its support for the latest and greatest.

**Comment by MasterKale** [comment]
@jstewmon I fixed the Netlify deployment issue with PR #74. If you pull in `master` into your branch the docs build step should start passing again. #67 and #68 will need that merge too.

**Comment by jstewmon** [comment]
@MasterKale I've rebased all three PRs 👍

**Review by MasterKale — APPROVED** [review]

**Pull request merged**
