### PR TITLE
chore(deps-dev): bump typescript from 3.9.7 to 4.0.5

### PR DESCRIPTION
**Pull request by jstewmon**
👋  Hi, I didn't have any cause other than I bothered checking if there were any compatibility issues with upgrading while I was poking around. I did find one compatibility issue with the new `delete` checks, for which fixes are provided.

https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#operands-for-delete-must-be-optional

### CODE REVIEW

**Comment by jstewmon** [comment]
This would need to follow #68 to avoid duplicating some of the changes in both PRs - rebasing on it should result in passing tests.

**Comment by MasterKale** [comment]
Thank you for your PR. There's nothing in TypeScript 4 that this project currently needs, though, so I'm going to close this for now.

**Comment by jstewmon** [comment]
Is there a reason you are resistant to keeping up with the current release? Eventually, you may want to use features available in a more recent version than you have currently, and it is likely that new TypeScript features will be adopted by _some_ dependency (either direct or transient).

**Comment by MasterKale** [comment]
I'm being conservative with dependencies in general because, as a security-oriented collection of libraries, I want to keep things as predictable and reliable as possible. I'm totally down for the idea of keeping all third-party dependencies as up-to-date as possible, but in the case of SimpleWebAuthn I'm choosing to be more stringent because I want developers who use it to know that their RP's won't suddenly break.

I've also been burned in the past with accidentally publishing a release that broke because of third-party versioning I have no control over. I was fortunate enough to have time to catch it and fix the issue, but my supply of time lately has significantly diminished due to life events and so I'm hesitant to approve updates like this in case something breaks. It'd be on me to make time to fix the issue and I can't guarantee that right now.

I'm totally down for upgrading to TypeScript 4 when a new SimpleWebAuthn feature would benefit from it, but upgrading for the sake of upgrading is less desirable right now.

**Comment by MasterKale** [comment]
@jstewmon I changed my mind on this, after all of your other contributions this one seemed like a no-brainer! Thank you again for the push 💪

**Pull request merged**
