### PR TITLE
fix/issue-114-browser-multi-bundle

### PR DESCRIPTION
**Pull request by MasterKale**
This PR updates @simplewebauthn/browser's build and bundling pipeline to generate artifacts to support a wider range of use cases. This includes:

- A new `"main"` build that targets ES2018
- A new `"browser"` build that targets ES5
- A UMD bundle that targets ES2018
- A UMD bundle that targets ES5 for deprecated browsers

This should address Issue #114.

### CODE REVIEW

**Comment by akanass** [comment]
I have done all optimisations inside my [PR](https://github.com/MasterKale/SimpleWebAuthn/pull/116) and all is much better now

**Comment by MasterKale** [comment]
A note to myself for tomorrow: why not update @swan/browser to not use as modern JS? If I refactor it to use "older"/more explicit JS I think there's a chance to avoid needing to fuss with tslib and multiple UMD bundles. The structure of the WebAuthn API is largely set for now, no need to "optimize" for unpacking future values via the spread operator (that's the real reason for jumping through all these bundling hoops)

**Comment by MasterKale** [comment]
I fired up BrowserStack and got some screenshots of the new ES5 UMD bundles in action, specifically testing support for `supportsWebAuthn()` after linking to the bundle in a `<script>` tag:

```html
<!-- Manually renamed dist/es5/index.umd.min.js -->
<script src="../index.umd.es2018.min.js"></script>
<script>
  (function() {
    const elemBegin = document.getElementById('btnBegin');
    const elemSuccess = document.getElementById('success');
    const elemError = document.getElementById('error');
    
    const supportsWebauthn = SimpleWebAuthnBrowser.supportsWebauthn;
    
    // Hide the Begin button if the browser is incapable of using WebAuthn
    if (!supportsWebauthn()) {
      elemBegin.style.display = 'none';
      elemError.innerText = "It seems this browser doesn't support WebAuthn...";
      return;
    }
    
    // ...
  })();
</script>
```

### IE 11
swan-browser-ie11-es5-umd

### Edge 17
swan-browser-edge17-es5-umd

**Comment by MasterKale** [comment]
I'm 99% satisfied this is ready to go.

That last 1% will involve me sleeping on this and then finding time in the next day or two to spin up a fresh Create-React-App project, [attempt to polyfill enough of it to run in IE11](https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill), and then try to use @simplewebauthn/browser as I would when building a typical SPA. If I can get `supportsWebAuthn()` to work in IE11 and Edge 17 then I'll publish this.

**Comment by akanass** [comment]
The job seems to have been done well, happy to see it happen successfully

**Comment by MasterKale** [comment]
Here's `supportsWebAuthn()` working in IE10 in a production build of a Create-React-App project:

Screen Shot 2021-04-08 at 8 31 52 AM

I only needed to do a couple of things with the React project:

1. `npm install react-app-polyfill`
2. Add `import 'react-app-polyfill/ie9';` to the top of **src/index.js**

And when I flipped over to TypeScript, I just needed to make sure **tsconfig.json** was set up with `"target": "es5"` and everything worked just fine.

**Comment by akanass** [comment]
@MasterKale so all was done successfully :D I am glad to hear that

**Pull request merged**
